apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: commit-carrier-allchannel-supplychain1-1
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: commit-carrier-allchannel-supplychain1-1
  chart:
    git: https://github.com/prasanths96/bevel.git
    ref: test
    path: platforms/hyperledger-fabric/charts/commit_chaincode
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://100.21.17.156:9696
      authpath: devcarrier-net-auth
      adminsecretprefix: secret/data/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secret/data/crypto/peerOrganizations/carrier-net/orderer
      secretpath: secret
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.org1ambassador.getthespiderman.com:8443
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.2
      name: supplychain
      version: 1
      sequence: 1
      commitarguments: '\"init\",\"\"'
      endorsementpolicies:  ''
    channel:
      name: allchannel
    endorsers:
      creator: carrier-net
      name:  carrier  manufacturer 
      corepeeraddress:  peer0.carrier-net.org3ambassador.getthespiderman.com:8443  peer0.manufacturer-net.org2ambassador.getthespiderman.com:8443 
      certificates:  LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNQakNDQWVTZ0F3SUJBZ0lVVlgyL1ptRzZEcUZVU0lTV2M0Mzl3OEoyWm4wd0NnWUlLb1pJemowRUF3SXcKZlRFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNVG93T0FZRFZRUUREREZqWVM1allYSnlhV1Z5TFc1bGRDNXZjbWN6CllXMWlZWE56WVdSdmNpNW5aWFIwYUdWemNHbGtaWEp0WVc0dVkyOXRNQjRYRFRJeU1EVXhNVEl3TVRJek5sb1gKRFRJMU1ESXlPREl3TVRJek5sb3dmVEVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUApNQTBHQTFVRUJ3d0dURzl1Wkc5dU1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1Ub3dPQVlEVlFRRERERmpZUzVqCllYSnlhV1Z5TFc1bGRDNXZjbWN6WVcxaVlYTnpZV1J2Y2k1blpYUjBhR1Z6Y0dsa1pYSnRZVzR1WTI5dE1Ga3cKRXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVrMFdkdU5xQm1WczhDcGFZa1llY0lWNGt5MlJpZ3ZkUwptWGFUV2p4UVB4c1JXdXNVUERMZlA3M1JDSTMzUHR3TnVqYjduRTRIdFJxUWhYVWg2a1F4U3FOQ01FQXdEd1lEClZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVkhROEJBZjhFQkFNQ0FhWXdIUVlEVlIwT0JCWUVGTFpxSTROYll0UnMKekxLUVU2SFJQd2toNFFLWk1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRQ3NiSCthQnRFbjZRZEZNTUpsMFB4WAp3RjJkRWFOQTQ1K1BYbS95a1Rxak9BSWdZazRjSjNzd0ExOFF1SVdGRktHSnVTQmkyZzh6dU1GNmFzczRPRVNLCkRFVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==  LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNWRENDQWZxZ0F3SUJBZ0lVYk9PM1VnSlZQalVmQTVWQkU2QkhCUmh6bjJFd0NnWUlLb1pJemowRUF3SXcKZ1ljeEN6QUpCZ05WQkFZVEFrTklNUTh3RFFZRFZRUUlEQVphZFhKcFkyZ3hEekFOQmdOVkJBY01CbHAxY21sagphREVWTUJNR0ExVUVDZ3dNVFdGdWRXWmhZM1IxY21WeU1UOHdQUVlEVlFRREREWmpZUzV0WVc1MVptRmpkSFZ5ClpYSXRibVYwTG05eVp6SmhiV0poYzNOaFpHOXlMbWRsZEhSb1pYTndhV1JsY20xaGJpNWpiMjB3SGhjTk1qSXcKTlRFeE1qQXhNRE0yV2hjTk1qVXdNakk0TWpBeE1ETTJXakNCaHpFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVgpCQWdNQmxwMWNtbGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm9NUlV3RXdZRFZRUUtEQXhOWVc1MVptRmpkSFZ5ClpYSXhQekE5QmdOVkJBTU1ObU5oTG0xaGJuVm1ZV04wZFhKbGNpMXVaWFF1YjNKbk1tRnRZbUZ6YzJGa2IzSXUKWjJWMGRHaGxjM0JwWkdWeWJXRnVMbU52YlRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQktrUwpzK0ZvR1Bob0t1ZWNiQzkrOVgrNU5vOEE3R040a21wQUJzWHFncEJFaDhraDhnUFc3aGFjVkM4blBCY1JpZDk5CmlrcE5NeUE3SGN5UHEyNjVMeXVqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUUQKQWdHbU1CMEdBMVVkRGdRV0JCUWdUdXJvM3pFbHY3bFVCSXRjaDZ0NVRmZ3J5REFLQmdncWhrak9QUVFEQWdOSQpBREJGQWlCeDlTMXpsVVVyMTBrelhNV2hrSFJxenJBUGR2OTNtNGNLZ2ovVUM4WGZqUUloQUphSkUrRjRPcHM0CmhFcXNhMDZER3NLQ1RkcFFhWmpyS0wvNXpveDB0MW1KCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0= 
