apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carrier-peer0
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: carrier-peer0
  chart:
    git: https://github.com/prasanths96/bevel.git
    ref: test
    path: platforms/hyperledger-fabric/charts/peernode    
  values:
    metadata:
      namespace: carrier-net
      images:
        couchdb: couchdb:3.1
        peer: hyperledger/fabric-peer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
        
    peer:
      name: peer0
      gossippeeraddress: peer0.carrier-net.org3ambassador.getthespiderman.com:8443
      gossipexternalendpoint: peer0.carrier-net.org3ambassador.getthespiderman.com:8443
      localmspid: carrierMSP
      loglevel: info
      tlsstatus: true
      builder: hyperledger/fabric-ccenv:2.2.2
      couchdb:
        username: carrier-user

    storage:
      peer:
        storageclassname: carriersc
        storagesize: 512Mi
      couchdb:
        storageclassname: carriersc
        storagesize: 1Gi

    vault:
      role: vault-role
      address: http://100.21.17.156:9696
      authpath: devcarrier-net-auth
      secretprefix: secret/data/crypto/peerOrganizations/carrier-net/peers/peer0.carrier-net
      secretambassador: secret/data/crypto/peerOrganizations/carrier-net/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: secret/data/credentials/carrier-net/couchdb/carrier?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: "haproxy"
      external_url_suffix: org3ambassador.getthespiderman.com

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
