apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: peer0-manufacturer-cli
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: peer0-manufacturer-cli
  chart:
    git: https://github.com/prasanths96/bevel.git
    ref: test
    path: platforms/hyperledger-fabric/charts/fabric_cli    
  values:
    metadata:
      namespace: manufacturer-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    storage:
      class: manufacturersc
      size: 256Mi
    vault:
      role: vault-role
      address: http://100.21.17.156:9696
      authpath: devmanufacturer-net-auth
      adminsecretprefix: secret/data/crypto/peerOrganizations/manufacturer-net/users/admin
      orderersecretprefix: secret/data/crypto/peerOrganizations/manufacturer-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    peer:
      name: peer0
      localmspid: manufacturerMSP
      tlsstatus: true
      address: peer0.manufacturer-net.org2ambassador.getthespiderman.com:8443
    orderer:
      address: orderer1.org1ambassador.getthespiderman.com:8443
