apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: chaincode-install-manufacturer-peer0-1
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: chaincode-install-manufacturer-peer0-1
  chart:
    git: https://github.com/prasanths96/bevel.git
    ref: test
    path: platforms/hyperledger-fabric/charts/install_chaincode
  values:
    metadata:
      namespace: manufacturer-net
      network:
        version: 2.2.2
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.manufacturer-net:7051
      localmspid: manufacturerMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://100.21.17.156:9696
      authpath: devmanufacturer-net-auth
      adminsecretprefix: secret/data/crypto/peerOrganizations/manufacturer-net/users/admin 
      orderersecretprefix: secret/data/crypto/peerOrganizations/manufacturer-net/orderer
      secretgitprivatekey: secret/data/credentials/manufacturer-net/git
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer3.org1ambassador.getthespiderman.com:8443
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.2
      name: supplychain
      version: 1
      lang: golang
      maindirectory: cmd
      repository:
        hostname: "github.com"
        git_username: "prasanths96"
        url: github.com/prasanths96/bevel.git
        branch: main
        path: examples/supplychain-app/fabric/chaincode_rest_server/chaincode/
      endorsementpolicies:  ''
