apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: manufacturer-net-ca
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: manufacturer-net-ca
  chart:
    git: https://github.com/prasanths96/bevel.git
    ref: test
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: manufacturer-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
    deployment:
      annotations:
    annotations:  
      service:
        - example1: example2
      pvc:
 
    server:
      name: ca
      tlsstatus: true
      admin: manufacturer-admin 
  
    storage:
      storageclassname: manufacturersc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://100.21.17.156:9696
      authpath: devmanufacturer-net-auth
      secretcert: secret/data/crypto/peerOrganizations/manufacturer-net/ca?ca.manufacturer-net-cert.pem
      secretkey: secret/data/crypto/peerOrganizations/manufacturer-net/ca?manufacturer-net-CA.key
      secretadminpass: secret/data/credentials/manufacturer-net/ca/manufacturer?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: haproxy
      type: peer
      external_url_suffix: org2ambassador.getthespiderman.com
